"""add fk indexes

Revision ID: 0002_indexes
Revises: 0001_baseline
Create Date: 2026-07-04 01:03:27.929119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_indexes'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_exercise_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_log_workout_id'), ['workout_id'], unique=False)

    with op.batch_alter_table('hidden_exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hidden_exercise_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('rotation_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rotation_entry_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_progression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_progression_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_user_id'))

    with op.batch_alter_table('user_progression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_progression_user_id'))

    with op.batch_alter_table('rotation_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rotation_entry_user_id'))

    with op.batch_alter_table('hidden_exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hidden_exercise_user_id'))

    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_log_workout_id'))

    with op.batch_alter_table('custom_exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_exercise_user_id'))

    # ### end Alembic commands ###
